load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "AstroLib",
    srcs = [
        "Common.cpp",
        "ConfigBuilderClass.cpp",
    ],
    hdrs = [
        "Common.hpp",
        "Config.hpp",
        "ConfigBuilderClass.hpp",
    ],
    deps = ["//utils:Utils"],
    visibility = ["//visibility:public"],
)
