load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "AstroLib",
    srcs = [
        "Common.cpp",
        "RasiBuilderClass.cpp",
    ],
    hdrs = [
        "Common.hpp",
        "Rasi.hpp",
        "RasiBuilderClass.hpp",
    ],
    visibility = ["//visibility:public"],
)
